kafka:
  topic: demo
  group: exchanges
spring:
  mvc:
    view:
      suffix: .html
  datasource:
    url: jdbc:mysql://mysql:3306/botdb?useSSL=false
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
